services:
  nextjs:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - "3200:3000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 5